---
# Run ansible-playbook (-i hosts) (--limit <hostname>) dotfiles.yml (-t <tag>)
- hosts: all
  vars_files:
    - vars/{{ ansible_hostname }}.yml
    - vars/gruvbox_palette.yml
  tasks:
      # init group
      # this group is the most essential. To use the rest these need to be run first
    - include: tasks/ansible.yml
    - include: tasks/zsh.yml
    - include: tasks/bin.yml
    #- include: tasks/packages.yml

      # browser group
    - include: tasks/firefox.yml
    - include: tasks/pentadactyl.yml
    - include: tasks/vimperator.yml

      # window manager group
    - include: tasks/themes.yml
    - include: tasks/gtk.yml
    - include: tasks/dunst.yml
    - include: tasks/i3.yml
    - include: tasks/feh.yml
    - include: tasks/nitrogen.yml
    - include: tasks/background.yml
    - include: tasks/compton.yml
    - include: tasks/fonts.yml
    - include: tasks/x.yml
    - include: tasks/desktop.yml

      # shell group
    - include: tasks/dircolors.yml
    - include: tasks/colors.yml
    - include: tasks/scripts.yml
    - include: tasks/ls++.yml
    - include: tasks/bash.yml
    - include: tasks/boxes.yml
    - include: tasks/fasd.yml
    - include: tasks/tmux.yml
    - include: tasks/screen.yml
    - include: tasks/termite.yml
    - include: tasks/ranger.yml
    - include: tasks/terminfo.yml

      # dev group
    - include: tasks/lein.yml
    - include: tasks/npm.yml
    - include: tasks/ctags.yml
    - include: tasks/git.yml
    - include: tasks/subversion.yml
    - include: tasks/idea.yml
    - include: tasks/tig.yml
    - include: tasks/vim.yml
    - include: tasks/sublime.yml
    - include: tasks/ruby.yml

      # misc
    - include: tasks/taskwarrior.yml
    - include: tasks/ncmpcpp.yml
    - include: tasks/gimp.yml
    - include: tasks/inkscape.yml
    - include: tasks/xboxdrv.yml
    - include: tasks/krita.yml
    - include: tasks/apvlv.yml

