---
- name: Symlink ansible user config
  file: src={{ dotfiles }}/ansible/{{ item.src }} dest={{ home }}/{{ item.dest }} state=link
  with_items:
    - { src: '.ansible.cfg', dest: '.ansible.cfg' }
    - { src: 'library', dest: '.ansible/library' }
    - { src: 'hosts', dest: '.ansible/hosts' }
  tags:
    - ansible
    - symlink
    - init
    - full

