---
- name: check for/create lib and bin directory
  file: path={{ home }}/{{ item }} state=directory mode=0755
  with_items:
    - lib
    - bin
  tags:
    - bin
    - init

- name: clone / update external libraries
  git: repo={{ item.repo }} dest={{ home }}/lib/{{ item.dest }} clone=yes update=yes
  with_items:
    - { repo: "https://github.com/fidian/ansi", dest: "ansi" }
    - { repo: "https://github.com/iye/lightsOn", dest: "lightsOn" }
    - { repo: "https://github.com/nonpop/xkblayout-state", dest: "xkblayout-state" }
    - { repo: "https://github.com/sampson-chen/sack", dest: "sack" }
    - { repo: "https://github.com/franks42/lein-repls", dest: "lein-repls" }
    #- { repo: "https://github.com/brandur/tmux-extra", dest: "tmux-extra" }
  tags:
    - bin
    - init

- name: build xkblayout-state
  command: make
  args:
    chdir: "{{ home }}/lib/xkblayout-state"
  tags:
    - bin
    - init

- name: install sack
  command: ./install_sack.sh
  args:
    chdir: "{{ home }}/lib/sack"
  tags:
    - bin
    - init

- name: set perissions for cljsh binary
  file: path={{ home }}/lib/lein-repls/bin/cljsh mode=0755
  tags:
    - bin
    - init

- name: symlink local binaries
  file: src={{ item.src }} dest={{ home }}/bin/{{ item.dest }} state=link
  with_items:
    - { src: "{{ home }}/lib/ansi/ansi", dest: "ansi" }
    - { src: "{{ home }}/lib/lightsOn/lightsOn.sh", dest: "lightsOn" }
    - { src: "{{ home }}/lib/xkblayout-state/xkblayout-state", dest: "xkblayout-state" }
    - { src: "{{ home }}/lib/lein-repls/bin/cljsh", dest: "cljsh" }
  tags:
    - bin
    - init
