- name: check for/create library and bin directory
  file: path={{ home }}/{{ item }} state=directory mode=0755
  with_items:
    - library
    - bin

- name: clone / update external libraries
  git: repo={{ item.repo }} dest={{ home }}/library/{{ item.dest }} clone=yes update=yes
  with_items:
    - { repo: "https://github.com/fidian/ansi", dest: "ansi" }
    - { repo: "https://github.com/iye/lightsOn", dest: "lightsOn" }
    - { repo: "https://github.com/nonpop/xkblayout-state", dest: "xkblayout-state" }

- name: build xkblayout-state
  command: make
  args:
    chdir: "{{ home }}/library/xkblayout-state"

- name: symlink local binaries
  file: src={{ item.src }} dest={{ home }}/{{ item.dest }} state=link
  with_items:
    - { src: "{{ home }}/library/ansi/ansi", dest: "bin/ansi" }
    - { src: "{{ home }}/library/lightsOn/lightsOn.sh", dest: "bin/lightsOn" }
    - { src: "{{ home }}/.scripts/chmon.sh", dest: "bin/chmon" }
    - { src: "{{ home }}/.scripts/bakc.sh", dest: "bin/bakc" }
    - { src: "{{ dotfiles }}/fatline/fatline.sh", dest: "bin/fatline" }
    - { src: "{{ home }}/.scripts/touchpad-toggle.sh", dest: "bin/touchpad-toggle" }
    - { src: "{{ home }}/library/xkblayout-state/xkblayout-state", dest: "bin/xkblayout-state" }
