---
# zsh being the preferred shell, I still track these
- name: Symlink git config to home
  file: dest={{home}}/{{item}} src={{dotfiles}}/git/{{item}} state=link
  with_items:
    - .gitconfig
    - .gitignore
