---
- hosts: lintilla
  vars_files:
  - ../vars/gruvbox_palette.yml
  tasks:
  #- name: Install i3-wm package if not present
    #become: True
    #pacman: name=i3-wm state=present

  - name: Create i3 config from template
    template: src={{ dotfiles }}/i3/{{ item }} dest={{ dotfiles }}/i3/config.gen backup=yes
    with_items:
      - config.j2
      - bar/lintilla/bar.j2 command={{ status_primary }} output={{ output_primary }}
      - bar/lintilla/bar.j2 command={{ status_secondary }} output={{ output_secondary }}
      - bar/lintilla/bar.j2 command={{ status_tertiary }} output={{ output_tertiary }}

  - name: Symlink i3 configuration
    file: path={{ home }}/.i3 src={{ dotfiles }}/i3 state=link
