---
# setup i3 window manager
- name: Install i3-wm package if not present
  pacman: name=i3-wm state=present

- name: Assemle i3 configuration
  template: src={{dotfiles}}/templates/{{item}} dest={{dotfiles}}/i3/i3.config backup=yes

- name: Symlink i3 configuration
  file: path={{home}}/.i3 src={{dotfiles}}/i3 state=link
