---
# setup i3 window manager
- name: Install i3-wm package if not present
  become: True
  pacman: name=i3-wm state=present

- name: Create i3 config from template
  template: src={{ dotfiles }}/i3/config.j2 dest={{ dotfiles }}/i3/config.gen backup=yes

- name: Symlink i3 configuration
  file: path={{ home }}/.i3 src={{ dotfiles }}/i3 state=link
