---
- name: check for/create library and bin directory
  file: path={{ home }}/{{ item }} state=directory mode=0755
  tags:
    - intellij
    - idea
    - dev
  with_items:
    - .IntelliJIdea15

# Setup leiningen config. Relies on AUR package!
- name: Symlink "IntellijIdea" configuration
  tags:
    - intellij
    - idea
    - dev
  file: dest={{ home }}/{{ item.dest }} src={{ dotfiles }}/idea/{{ item.src }} state=link
  with_items:
    - { src: '.ideavimrc', dest: '.ideavimrc' }
    - { src: 'config', dest: '.IntelliJIdea15/config' }

