# Use this mainly so-as not to use elevated privileges every time a role/task is needed
- name: Install missing packages from Arch linux official repos
  pacman: name={{ item }} state=present
  with_items:
    -  ack
    -  acpi
    -  agave
    -  alex
    -  alsa-utils
    -  android-tools
    -  android-udev
    -  ansible
    -  apache
    -  arch-wiki-docs
    -  arch-wiki-lite
    -  aspell-en
    -  atool
    -  autoconf
    -  autofs
    -  automake
    -  bar
    -  bash
    -  bash-completion
    -  bind-tools
    -  binutils
    -  bison
    -  bleachbit
    -  bzip2
    -  cabal-install
    -  calc
    -  calligra-krita
    -  ccze
    -  clamav
    -  clang
    -  clojure
    -  colordiff
    -  colorgcc
    -  conky
    -  coreutils
    -  cryptsetup
    -  ctags
    -  deluge
    -  device-mapper
    -  dfc
    -  dhcpcd
    -  dialog
    -  diffutils
    -  dkms
    -  dmenu
    -  docker
    -  dunst
    -  dzen2
    -  e2fsprogs
    -  elinks
    -  envoy
    -  etckeeper
    -  ethtool
    -  evince
    -  evtest
    -  faenza-icon-theme
    -  fakeroot
    -  fdupes
    -  feh
    -  ffmpeg-compat
    -  file
    -  filesystem
    -  findutils
    -  firefox
    -  flex
    -  fontforge
    -  freemind
    -  freerdp
    -  gawk
    -  gcc-multilib
    -  gcolor2
    -  gdb
    -  gettext
    -  ghc
    -  gifsicle
    -  gimp
    -  git
    -  gksu
    -  glances
    -  glibc
    -  gnome-characters
    -  gnome-keyring
    -  go
    -  gparted
    -  gpick
    -  gptfdisk
    -  graphicsmagick
    -  grep
    -  groff
    -  grub
    -  gst-libav
    -  gst-plugins-good
    -  gtk2
    -  gucharmap
    -  gvim
    -  gzip
    -  haddock
    -  happy
    -  hddtemp
    -  hexedit
    -  highlight
    -  htop
    -  hwinfo
    -  i3-wm
    -  i3lock
    -  i3status
    -  imagemagick
    -  inetutils
    -  inkscape
    -  inotify-tools
    -  iproute2
    -  iputils
    -  irssi
    -  java-jline
    -  java-rhino
    -  jfsutils
    -  keepassx
    -  keychain
    -  less
    -  lib32-alsa-plugins
    -  lib32-fakeroot
    -  lib32-glu
    -  lib32-libltdl
    -  lib32-nvidia-libgl
    -  libnewt
    -  libreoffice-fresh
    -  libtool
    -  licenses
    -  linphone
    -  linux
    -  linux-headers
    -  lm_sensors
    -  logrotate
    -  lxinput
    -  lxpanel
    -  lxrandr
    -  m4
    -  make
    -  man-db
    -  man-pages
    -  mediainfo
    -  meld
    -  mlocate
    -  mopidy
    -  most
    -  mpd
    -  mplayer
    -  mtpaint
    -  mutt
    -  mypaint
    -  namcap
    -  nano
    -  ncdu
    -  ncmpcpp
    -  netctl
    -  nfs-utils
    -  nitrogen
    -  nmap
    -  nodejs
    -  npm
    -  ntfs-3g
    -  ntop
    -  numix-themes
    -  numlockx
    -  nvidia
    -  nvidia-libgl
    -  obconf
    -  oblogout
    -  obmenu
    -  openbox
    -  openbox-themes
    -  opencl-nvidia
    -  openssh
    -  openvpn
    -  os-prober
    -  otf-fira-mono
    -  otf-fira-sans
    -  pacman
    -  pandoc
    -  patch
    -  pavucontrol
    -  pciutils
    -  pdnsd
    -  perl
    -  perl-anyevent
    -  perl-anyevent-i3
    -  perl-json-xs
    -  perlpanel
    -  phantomjs
    -  pidgin
    -  pidgin-encryption
    -  pidgin-libnotify
    -  pidgin-otr
    -  pkg-config
    -  pkgfile
    -  playonlinux
    -  polkit
    -  ponymix
    -  procps-ng
    -  progress
    -  psmisc
    -  pulseaudio
    -  pulseaudio-alsa
    -  pulseaudio-jack
    -  pulseaudio-zeroconf
    -  python-chardet
    -  python-pip
    -  python-pygments
    -  python2
    -  python2-passlib
    -  qemu
    -  qiv
    -  ranger
    -  refind-efi
    -  reflector
    -  reiserfsprogs
    -  remmina
    -  rhino
    -  rkhunter
    -  rlwrap
    -  rsync
    -  rxvt-unicode-terminfo
    -  s-nail
    -  sassc
    -  screen
    -  scrot
    -  seahorse
    -  sed
    -  shadow
    -  sl
    -  smplayer
    -  smplayer-skins
    -  smtube
    -  source-highlight
    -  spacefm
    -  steam
    -  stow
    -  subversion
    -  sudo
    -  sysfsutils
    -  sysstat
    -  systemd-sysvcompat
    -  tar
    -  task
    -  termite
    -  texinfo
    -  the_silver_searcher
    -  thunderbird
    -  tig
    -  tk
    -  tmux
    -  traceroute
    -  transmission-cli
    -  transmission-gtk
    -  tree
    -  ttf-fira-mono
    -  ttf-fira-sans
    -  udevil
    -  ufw
    -  unhide
    -  unrar
    -  unzip
    -  urxvt-perls
    -  usbutils
    -  util-linux
    -  vi
    -  vicious
    -  vifm
    -  vimpager
    -  w3m
    -  which
    -  whois
    -  wicd
    -  wicd-gtk
    -  wireshark-cli
    -  wol
    -  wyrd
    -  x11-ssh-askpass
    -  xautolock
    -  xbindkeys
    -  xclip
    -  xdg-user-dirs
    -  xf86-video-nouveau
    -  xfsprogs
    -  xloadimage
    -  xorg-iceauth
    -  xorg-luit
    -  xorg-server-devel
    -  xorg-smproxy
    -  xorg-utils
    -  xorg-x11perf
    -  xorg-xauth
    -  xorg-xbacklight
    -  xorg-xcmsdb
    -  xorg-xcursorgen
    -  xorg-xfd
    -  xorg-xfontsel
    -  xorg-xgamma
    -  xorg-xhost
    -  xorg-xinit
    -  xorg-xinput
    -  xorg-xkbevd
    -  xorg-xkbutils
    -  xorg-xlsfonts
    -  xorg-xmodmap
    -  xorg-xpr
    -  xorg-xrandr
    -  xorg-xrefresh
    -  xorg-xset
    -  xorg-xwd
    -  xorg-xwud
    -  xscreensaver
    -  youtube-viewer
    -  zip
    -  zsh
    -  zsh-completions
    -  zsh-doc
    -  zsh-lovers
    -  zshdb

# infinality fonts
  #- otf-fira-mono
  #- otf-fira-sans
  #- otf-neris
  #- ttf-aller
  #- ttf-envy-code-r
  #- ttf-fira-mono
  #- ttf-fira-sans
  #- ttf-font-awesome


# AUR packages
  #- mopidy-mpris
  #- symlinks
  #- toilet
  #- numix-icon-theme-git
  #- atom-editor-bin
  #- spotify
  #- aur-git
  #- aura-bin
  #- boxes
  #- byobu
  #- checkbashisms
  #- colormake
  #- colorsvn
  #- compton
  #- cower-git
  #- fasd-git
  #- firefox-developer
  #- gbdfed
  #- google-chrome
  #- google-chrome-beta
  #- gtk-theme-iris-dark-git
  #- i3blocks
  #- leiningen
  #- lemonbar-git
  #- libcurl-compat
  #- lighttable
  #- ls++-git
  #- memtest86-efi
  #- moka-icon-theme-git
  #- mopidy-mpris
  #- mopidy-spotify
  #- numix-icon-theme-git
  #- otf-neris
  #- pacaur-git
  #- package-query
  #- pkgtools
  #- playerctl
  #- rofi-git
  #- rxvt-unicode-256xresources
  #- scudcloud
  #- seafile-client
  #- seafile-client-cli
  #- slack-chat
  #- solaar-git
  #- spotify
  #- steam-fonts
  #- steamos-xpad-dkms
  #- sublime-text-dev
  #- symlinks
  #- toilet
  #- ttf-aller
  #- ttf-envy-code-r
  #- ttf-font-awesome
  #- leiningen
  #- ls++-git



