---
# Setup ls++ config. Relies on AUR package!
- name: Symlink "Subversion" configuration
  tags:
    - svn
    - subversion
    - dev
  file: dest={{ home }}/.subversion src={{ dotfiles }}/subversion state=link
