---
- name: Symlink taskwarrior data
  tags:
    - tasks
    - taskwarrior
    - misc
  file: dest={{ home }}/{{ item }} src={{ dotfiles }}/taskwarrior/{{ item }} state=link
  with_items:
    - .taskrc
    - .task
