[general]
default_icon = ""

[options]
remove_duplicates = true

[icons]
Firefox = ""
Firefox-dev = ""
Termite = ""
Thunderbird = ""
Google-chrome-unstable = ""
Google-chrome= ""
Spotify = ""
libreoffice-calc = ""
"Gimp-2.10" = ""
Transmission-gtk = ""
com-eviware-soapui-SoapUI = ""
"Org.gnome.Nautilus" = ""
"web.whatsapp.com" = ""
"Discord" = ""
Alacritty = ""
kitty = ""
Steam = ""
REAPER = ""
Bitwig = ""

[aliases]
firefoxdeveloperedition = "Firefox-dev"
"web.whatsapp.com" = "Whatsapp"
libreoffice-calc = "Calc"
firefox = "Firefox"
Google-chrome-unstable = "Chrome-dev"
Google-chrome = "Chrome"
"Gimp-\\d\\.\\d\\d" = "Gimp"
Transmission-gtk = "Transmission"
com-eviware-soapui-SoapUI = "SoapUI"
"Org.gnome.Nautilus" = "Nautilus"
"^discord$" = "Discord"
"com\\.bitwig\\.BitwigStudio" = "Bitwig"
steam = "Steam"
