[general]
# separator = "  "

[options]
remove_duplicates = true

[icons]
default_icon = ""
"Firefox" = ""
"Firefox Developer" = ""
"Firefox Media" = ""
Termite = ""
Thunderbird = ""
Chrome-dev = ""
Chrome= ""
Spotify = ""
libreoffice-calc = ""
"Gimp-2.10" = ""
Transmission-gtk = ""
com-eviware-soapui-SoapUI = ""
"Nautilus" = ""
"web.whatsapp.com" = ""
"Discord" = ""
Alacritty = ""
kitty = ""
Steam = ""
REAPER = ""
Bitwig = ""
Slack = ""
Evince = ""
Gpick = ""
Shortwave = ""
Mixer = ""
Gedit =""

[aliases.app_id]
firefox-developer-edition = "Firefox Developer"
libreoffice-calc = "Calc"
"^firefox$" = "Firefox"
"^firefox-media$" = "Firefox Media"
Google-chrome-unstable = "Chrome-dev"
Google-chrome = "Chrome"
Transmission-gtk = "Transmission"
"org.gnome.Nautilus" = "Nautilus"
"com\\.bitwig\\.BitwigStudio" = "Bitwig"
jetbrains-idea-ce = "IntelliJ"
thunderbird = "Thunderbird"
shortwave = "Shortwave"
pavucontrol = "Mixer"

[aliases.class]
steam = "Steam"
"^discord$" = "Discord"
"Gimp-\\d\\.\\d\\d" = "Gimp"

# [aliases.instance]
# "open.spotify.com" = "Spotify"
