[general]
default_icon = ""

[options]
remove_duplicates = true

[icons]
"Firefox" = ""
"Firefox Developer" = ""
"Firefox Media" = ""
Termite = ""
Thunderbird = ""
Chrome-dev = ""
Chrome= ""
Spotify = ""
libreoffice-calc = ""
"Gimp-2.10" = ""
Transmission-gtk = ""
com-eviware-soapui-SoapUI = ""
"Nautilus" = ""
"web.whatsapp.com" = ""
"Discord" = ""
Alacritty = ""
kitty = ""
Steam = ""
REAPER = ""
Bitwig = ""
Slack = ""
Evince = ""
Gpick = ""

[aliases.class]
firefox-developer-edition = "Firefox Developer"
libreoffice-calc = "Calc"
"^firefox$" = "Firefox"
"^firefox-media$" = "Firefox Media"
Google-chrome-unstable = "Chrome-dev"
Google-chrome = "Chrome"
"Gimp-\\d\\.\\d\\d" = "Gimp"
Transmission-gtk = "Transmission"
com-eviware-soapui-SoapUI = "SoapUI"
"org.gnome.Nautilus" = "Nautilus"
"^discord$" = "Discord"
"com\\.bitwig\\.BitwigStudio" = "Bitwig"
steam = "Steam"
jetbrains-idea-ce = "IntelliJ"
thunderbird = "Thunderbird"

[aliases.instance]
"open.spotify.com" = "Spotify"

