[icons]
firefox = ""
firefoxdeveloperedition = ""
Termite = ""
Thunderbird = ""
Google-chrome-unstable = ""
Google-chrome= ""
Spotify = ""
libreoffice-calc = ""
"Gimp-2.10" = ""
Transmission-gtk = ""

[aliases]
firefoxdeveloperedition = "Firefox-dev"
libreoffice-calc = "Calc"
firefox = "Firefox"
Google-chrome-unstable = "Chrome-dev"
Google-chrome = "Chrome"
"Gimp-2.10" = "Gimp"
Transmission-gtk = "Transmission"
