[general]
default_icon = ""

[options]
no_names = false
remove_duplicates = false
use_instance = false

[icons]
firefox = ""
firefoxdeveloperedition = ""
Termite = ""
Thunderbird = ""
Google-chrome-unstable = ""
Google-chrome= ""
Spotify = ""
libreoffice-calc = ""
"Gimp-2.10" = ""
Transmission-gtk = ""
com-eviware-soapui-SoapUI = ""
"Org.gnome.Nautilus" = ""
"web.whatsapp.com" = ""

[aliases]
firefoxdeveloperedition = "Firefox-dev"
google-chrome-unstable = "Chrome unstable"
"web.whatsapp.com" = "Whatsapp"
libreoffice-calc = "Calc"
firefox = "Firefox"
Google-chrome-unstable = "Chrome-dev"
Google-chrome = "Chrome"
"Gimp-2.10" = "Gimp"
Transmission-gtk = "Transmission"
com-eviware-soapui-SoapUI = "SoapUI"
"Org.gnome.Nautilus" = "Nautilus"
