---
# setup i3 window manager
- name: Install i3-wm package if not present
  pacman: name=i3-wm state=present

- name: Symlink i3 configuration
  file: path={{home}}/.i3 src={{dotfiles}}/i3 state=link
