---
- name: Check for "ctags" package, and install if not present
  become: True
  pacman: name=ctags state=present

- name: Symlink ctags config
  file: path={{home}}/.ctags src={{dotfiles}}/ctags/.ctags state=link
