---
- name: i3-wm config role
  hosts: "{{ target }}"
  vars_files: "{{ dotfiles }}/vars/gruvbox_palette.yml"
  tasks:
    - name: Install i3-wm package if missing
      become: true
      pacman: name=i3-wm state=present

    - name: Create i3 config from template
      template: src={{ dotfiles }}/i3/config.j2 dest={{ dotfiles }}/i3/config.gen backup=yes

    - name: Symlink i3 configuration
      file: path={{ home }}/.i3 src={{ dotfiles }}/i3 state=link
